version: '3.8'

services:
  backend:
    image: slotsync-backend
    build:
      context: ./slot_sync_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/slotsyncDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - AWS_ACCESS_KEY_ID=AKIA2UC3EYQW2RS3VB7E
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_S3_BUCKET=slotsync
    depends_on:
      - db

  frontend:
    image: slotsync-frontend
    build:
      context: ./slot_sync_frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slotsyncDB
    ports:
      - "5432:5432"
